name: kitchen-flow

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: kitchen_flow
      POSTGRES_USER: kitchen_flow
      POSTGRES_PASSWORD: kitchen_flow_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kitchen_flow -d kitchen_flow"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postgres-data:
  rabbitmq-data:
