@backend_HostAddress = http://localhost:5196

GET {{backend_HostAddress}}/
Accept: application/json

###

POST {{backend_HostAddress}}/orders
Content-Type: application/json

{
  "customerName": "Gus",
  "pizza": "Calabresa"
}

###
